# Generated by Django 5.1.4 on 2024-12-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimalism', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
